package mx.tiid.marhnos.schedule.model;
// Generated 25/04/2016 08:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Actividadesasignadas generated by hbm2java
 */
public class Actividadesasignadas implements java.io.Serializable {

	private Integer idActividadAsignada;
	private Causasincumplimiento causasincumplimiento;
	private Actividades actividades;
	private Date fechaAsignada;
	private Date fechaCompromiso;
	private Date fechaActualizada;
	private Boolean activo;
	private String comentario;
	private Integer numeroSemana;
	private Integer anio;

	public Actividadesasignadas() {
	}

	public Actividadesasignadas(Causasincumplimiento causasincumplimiento, Actividades actividades) {
		this.causasincumplimiento = causasincumplimiento;
		this.actividades = actividades;
	}

	public Actividadesasignadas(Causasincumplimiento causasincumplimiento, Actividades actividades, Date fechaAsignada,
			Date fechaCompromiso, Date fechaActualizada, Boolean activo, String comentario, Integer numeroSemana,
			Integer anio) {
		this.causasincumplimiento = causasincumplimiento;
		this.actividades = actividades;
		this.fechaAsignada = fechaAsignada;
		this.fechaCompromiso = fechaCompromiso;
		this.fechaActualizada = fechaActualizada;
		this.activo = activo;
		this.comentario = comentario;
		this.numeroSemana = numeroSemana;
		this.anio = anio;
	}

	public Integer getIdActividadAsignada() {
		return this.idActividadAsignada;
	}

	public void setIdActividadAsignada(Integer idActividadAsignada) {
		this.idActividadAsignada = idActividadAsignada;
	}

	public Causasincumplimiento getCausasincumplimiento() {
		return this.causasincumplimiento;
	}

	public void setCausasincumplimiento(Causasincumplimiento causasincumplimiento) {
		this.causasincumplimiento = causasincumplimiento;
	}

	public Actividades getActividades() {
		return this.actividades;
	}

	public void setActividades(Actividades actividades) {
		this.actividades = actividades;
	}

	public Date getFechaAsignada() {
		return this.fechaAsignada;
	}

	public void setFechaAsignada(Date fechaAsignada) {
		this.fechaAsignada = fechaAsignada;
	}

	public Date getFechaCompromiso() {
		return this.fechaCompromiso;
	}

	public void setFechaCompromiso(Date fechaCompromiso) {
		this.fechaCompromiso = fechaCompromiso;
	}

	public Date getFechaActualizada() {
		return this.fechaActualizada;
	}

	public void setFechaActualizada(Date fechaActualizada) {
		this.fechaActualizada = fechaActualizada;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Integer getNumeroSemana() {
		return this.numeroSemana;
	}

	public void setNumeroSemana(Integer numeroSemana) {
		this.numeroSemana = numeroSemana;
	}

	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

}
