package mx.tiid.marhnos.schedule.model;
// Generated 25/04/2016 08:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Actividades generated by hbm2java
 */
public class Actividades implements java.io.Serializable {

	private Integer idActividad;
	private Proyectos proyectos;
	private Usuarios usuarios;
	private String descripcion;
	private Boolean activo;
	private Set actividadesasignadases = new HashSet(0);

	public Actividades() {
	}

	public Actividades(Proyectos proyectos, Usuarios usuarios) {
		this.proyectos = proyectos;
		this.usuarios = usuarios;
	}

	public Actividades(Proyectos proyectos, Usuarios usuarios, String descripcion, Boolean activo,
			Set actividadesasignadases) {
		this.proyectos = proyectos;
		this.usuarios = usuarios;
		this.descripcion = descripcion;
		this.activo = activo;
		this.actividadesasignadases = actividadesasignadases;
	}

	public Integer getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(Integer idActividad) {
		this.idActividad = idActividad;
	}

	public Proyectos getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Proyectos proyectos) {
		this.proyectos = proyectos;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public Set getActividadesasignadases() {
		return this.actividadesasignadases;
	}

	public void setActividadesasignadases(Set actividadesasignadases) {
		this.actividadesasignadases = actividadesasignadases;
	}

}
