package mx.tiid.marhnos.schedule.model;
// Generated 25/04/2016 08:33:30 AM by Hibernate Tools 3.4.0.CR1

/**
 * Actividadesincumplidas generated by hbm2java
 */
public class Actividadesincumplidas implements java.io.Serializable {

	private Integer idActividadIncumplida;
	private Reportes reportes;
	private String nombre;
	private String fechaCompromiso;
	private String area;

	public Actividadesincumplidas() {
	}

	public Actividadesincumplidas(Reportes reportes) {
		this.reportes = reportes;
	}

	public Actividadesincumplidas(Reportes reportes, String nombre, String fechaCompromiso, String area) {
		this.reportes = reportes;
		this.nombre = nombre;
		this.fechaCompromiso = fechaCompromiso;
		this.area = area;
	}

	public Integer getIdActividadIncumplida() {
		return this.idActividadIncumplida;
	}

	public void setIdActividadIncumplida(Integer idActividadIncumplida) {
		this.idActividadIncumplida = idActividadIncumplida;
	}

	public Reportes getReportes() {
		return this.reportes;
	}

	public void setReportes(Reportes reportes) {
		this.reportes = reportes;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFechaCompromiso() {
		return this.fechaCompromiso;
	}

	public void setFechaCompromiso(String fechaCompromiso) {
		this.fechaCompromiso = fechaCompromiso;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

}
