package mx.tiid.marhnos.schedule.model;
// Generated 25/04/2016 08:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Causasincumplimiento generated by hbm2java
 */
public class Causasincumplimiento implements java.io.Serializable {

	private Integer idCausaIncumplimiento;
	private String nombre;
	private Set actividadesasignadases = new HashSet(0);

	public Causasincumplimiento() {
	}

	public Causasincumplimiento(String nombre, Set actividadesasignadases) {
		this.nombre = nombre;
		this.actividadesasignadases = actividadesasignadases;
	}

	public Integer getIdCausaIncumplimiento() {
		return this.idCausaIncumplimiento;
	}

	public void setIdCausaIncumplimiento(Integer idCausaIncumplimiento) {
		this.idCausaIncumplimiento = idCausaIncumplimiento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getActividadesasignadases() {
		return this.actividadesasignadases;
	}

	public void setActividadesasignadases(Set actividadesasignadases) {
		this.actividadesasignadases = actividadesasignadases;
	}

}
