package mx.tiid.marhnos.schedule.model;
// Generated 25/04/2016 08:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Proyectos generated by hbm2java
 */
public class Proyectos implements java.io.Serializable {

	private Integer idProyecto;
	private String nombre;
	private Boolean activo;
	private Set actividadeses = new HashSet(0);

	public Proyectos() {
	}

	public Proyectos(String nombre, Boolean activo, Set actividadeses) {
		this.nombre = nombre;
		this.activo = activo;
		this.actividadeses = actividadeses;
	}

	public Integer getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(Integer idProyecto) {
		this.idProyecto = idProyecto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public Set getActividadeses() {
		return this.actividadeses;
	}

	public void setActividadeses(Set actividadeses) {
		this.actividadeses = actividadeses;
	}

}
