package mx.tiid.marhnos.schedule.model;
// Generated 25/04/2016 08:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Reportes generated by hbm2java
 */
public class Reportes implements java.io.Serializable {

	private Integer idReporte;
	private String nombre;
	private Set acumuladoses = new HashSet(0);
	private Set actividadesincumplidases = new HashSet(0);

	public Reportes() {
	}

	public Reportes(String nombre, Set acumuladoses, Set actividadesincumplidases) {
		this.nombre = nombre;
		this.acumuladoses = acumuladoses;
		this.actividadesincumplidases = actividadesincumplidases;
	}

	public Integer getIdReporte() {
		return this.idReporte;
	}

	public void setIdReporte(Integer idReporte) {
		this.idReporte = idReporte;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAcumuladoses() {
		return this.acumuladoses;
	}

	public void setAcumuladoses(Set acumuladoses) {
		this.acumuladoses = acumuladoses;
	}

	public Set getActividadesincumplidases() {
		return this.actividadesincumplidases;
	}

	public void setActividadesincumplidases(Set actividadesincumplidases) {
		this.actividadesincumplidases = actividadesincumplidases;
	}

}
