package mx.tiid.marhnos.schedule.model;
// Generated 25/04/2016 08:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Semanas generated by hbm2java
 */
public class Semanas implements java.io.Serializable {

	private Integer idSemana;
	private Integer numeroSemana;
	private Date fechaInicio;
	private Date fechaFin;
	private Integer anio;

	public Semanas() {
	}

	public Semanas(Integer numeroSemana, Date fechaInicio, Date fechaFin, Integer anio) {
		this.numeroSemana = numeroSemana;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.anio = anio;
	}

	public Integer getIdSemana() {
		return this.idSemana;
	}

	public void setIdSemana(Integer idSemana) {
		this.idSemana = idSemana;
	}

	public Integer getNumeroSemana() {
		return this.numeroSemana;
	}

	public void setNumeroSemana(Integer numeroSemana) {
		this.numeroSemana = numeroSemana;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

}
